### ISSUE TITLE
Implement .Login and remove token restriction

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault-ruby#1]
/cc @armon it would be great if you could provide some examples of what that might look like :smile:

**Comment by kaelumania** [comment]
i think that this means that one should be able to query the tls certificate auth backend (or another one) without providing a token (see https://github.com/hashicorp/vault-ruby/blob/master/lib/vault/client.rb#L127). Further one has to be able to provide a key file (see tls auth backend and https://github.com/hashicorp/vault-ruby/blob/master/lib/vault/client.rb#L192) in order to authenticate via tls.

**Comment by sethvargo** [comment]
Although not all auths are done, most of them are done. Individual auths can be implemented in followup tickets.
