### ISSUE TITLE
Vault::Client public?

### ISSUE THREAD

**Issue by sheldonh** [hashicorp/vault-ruby#28]
The README illustrates the use of the super-meta Vault module. It doesn't illustrate use of the object-oriented Vault::Client class.

Is it future-proof to use `Vault::Client` directly?

**Comment by sethvargo** [comment]
Hi @sheldonh 

I think the very last paragraph in the [Usage](https://github.com/hashicorp/vault-ruby#usage) section describes this:

> If you do not want the Vault singleton, of if you need to communicate with multiple Vault servers at once, you can create indepenent client objects:
> 
>     client_1 = Vault::Client.new(address: "https://vault.mycompany.com")
>     client_2 = Vault::Client.new(address: "https://other-vault.mycompany.com")

It's definitely future-proof; in fact the Vault module just delegates to a client. However, since not everyone is familiar with OOP, the README uses the Vault module as the primary documentation. :smile: 

You may also be interested in the Yarddoc, since the README does not list every possible command and function.

**Comment by sheldonh** [comment]
Doh. Sorry, Seth.
